config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end

  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article #{@article.title} created!"

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article #{@article.title} updated!"


    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    flash.notice = "Article #{@article.title} deleted!"


    redirect_to articles_path
  end

  def tag_list
    @article = Article.find(params[:id])
    @article.tags.join(", ")
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CommentsHelper
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h3>Comment By: <%= comment.author_name %> </h3>
  <p><%= comment.body %>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_ids %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<%= link_to 'Create a New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><%= @article.body %></p>
<h3>Comments(<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<h3>Post a Comment</h3>
<%= render partial: 'comments/form' %>
<%= link_to '<<Back to Articles List', articles_path %><br />
<%= link_to 'Edit', edit_article_path %><br />
<%= link_to 'Delete', article_path(@article), method: 'delete', data: {confirm: 'Are you sure?'} %>

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment] do |f| %>
  <p>
    <%= f.label :your_name %><br />
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :your_comment %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Post' %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>Tags list</h1>
<% @tags.each do |tag| %>
  <li><%= tag.name %></li>
  <%= link_to "Delete #{Tag.name}", tag_path(tag), method: 'delete', data: {confirm: 'Are you sure?'} %>
<% end %>

app/views/tags/show.html.erb
<h1>Articles tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>